### ISSUE TITLE
Migration - Supported Patterns - Description for Recipient List Asynchronous is missing

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-integration-suite#79] opened 2024-06-18 06:54 UTC
### Issue description

The section "Recipient List Asynchronous" has no text or figures.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Supported Patterns

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/supported-templates#loiob5d43f624696473b93b812cdc36277ad

**Comment by SrutiSagaram** [comment] 2024-06-18 07:27
Hi @sebastianesch 
Thank you for your feedback. We will take a look and get back to you.

**Comment by Karunaharan** [comment] 2024-06-19 11:02
Hi @sebastianesch - the issue is fixed now. Thanks for letting us know.

**Closed by Karunaharan** 2024-06-19 11:02 UTC
Labels: contribution, size/s, type/other
