### ISSUE TITLE
Typo in Point-to-Point Synchronous 

### ISSUE THREAD

**Issue by Jay-SAP** [SAP-docs/btp-integration-suite#90] opened 2024-07-18 22:50 UTC
### Issue description

Typo in Point-to-Point Synchronous 

### Feedback Type (Optional)

spelling or grammar

### Page Title on SAP Help Portal (prefilled)

Supported Patterns

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/supported-templates?q=Integration%20Suite%20Migration%20Tooling#loio270776550dc34dbe97cb95403810f93f

**Comment by SrutiSagaram** [comment] 2024-07-19 03:19
Hi @Jay-SAP 
Thank you for the feedback. We will check and get back.

**Comment by Karunaharan** [comment] 2024-07-23 13:08
Hi @Jay-SAP,
Thanks for the feedback. The issue is fixed now and you can expect the changes in a couple of hours.

**Closed by Karunaharan** 2024-07-23 13:08 UTC
Labels: contribution, size/s, type/spelling-grammar
